# Group Tasks {-}

The group tasks in this lab will **not be assessed**, however they do offer good practise into writing your own code in `R`.

## Pregnancies Questions {-}

In 2004, the state of North Carolina released a large data set containing information on births recorded in this state. This data set is useful to researchers studying the relation between habits and practices of expectant mothers and the birth of their children. We will work with a random sample of observations from this data set.

Load the `nc` data set into your workspace by typing the following code in an Rscript file in your local Rstudio.

```{r ndfq1, eval = TRUE, echo = TRUE}
download.file("http://www.openintro.org/stat/data/nc.RData", destfile = "nc.RData")
load("nc.RData")
```

Before attempting the following exercises, explore the data as much or as little as you like using code from this Lab.

<br>

### Task 1 {-}

Calculate a 95% confidence interval for the average length of pregnancies (`weeks`). Note that since you’re doing inference on a single population parameter, there is no explanatory variable.

<br>

**Complete the following sentence, giving your answers to 2 decimal places.**
We are 95% certain that the average length of pregnancy for the population of women is between `r fitb(38.28)` and `r fitb(38.66)` weeks.

<br>

### Task 2 {-}

Calculate a new confidence interval for the same parameter at the 90% confidence level.

<br>

**Complete the following sentence, giving your answers to 2 decimal places.**
We are 90% certain that the average length of pregnancy for the population of women is between `r fitb(38.31)` and `r fitb(38.63)` weeks.

<br>

### Task 3 {-}

Conduct a hypothesis test evaluating whether the average weight gained by younger mothers is different than the average weight gained by mature mothers.

**Hint** Create a 95% confidence interval for the difference in mean weight gained between the two age groups. Don't forget to calculate a new standard error to use.

<br>

**What are your conclusions from this hypothesis test?**

a)  Given that the confidence interval contains 0, we reject the null hypothesis and conclude that there is a statistically significant difference in weight gained between younger and mature mothers in the population.

b)  Given that the confidence interval does not contain 0, we reject the null hypothesis and conclude that there is a statistically significant difference in weight gained between younger and mature mothers in the population.

c)  Given that the confidence interval does not contain 0, we do not reject the null hypothesis and conclude that there is no statistically significant difference in weight gained between younger and mature mothers in the population.

d)  Given that the confidence interval contains 0, we do not reject the null hypothesis and conclude that there is no statistically significant difference in weight gained between younger and mature mothers in the population.

<br>

### Task 4 {-}

Create side-by-side boxplots of the mothers' age (`mage`) for the two group; "mature mom" and "younger mom".

<br>

**Based on these boxplots, what would you say the age cutoff for a mother to be classified as a "younger mom" is?**

a)  25

b)  30

c)  35

d)  40

<br>
<br>





















